[theme]
base = "light"
primaryColor = "#0E9488"
backgroundColor = "#F4F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#152331"
font = "sans serif"

[server]
maxUploadSize = 15
enableXsrfProtection = true

[browser]
gatherUsageStats = false
